---
- name: Install the package "python3-pip"
  apt:
    name: python3-pip
  become: yes

- name: Install the package "python3-dev"
  apt:
    name: python3-dev
  become: yes

- name: Install python modules
  pip:
    name:
      - numpy
      - matplotlib
      - pandas
      - casadi
