---
  - name: add koide3s repositories
    become: yes
    block:
    - apt_key:
        url: https://koide3.github.io/ppa/ubuntu2204/KEY.gpg
        keyring: /etc/apt/trusted.gpg.d/koide3_ppa.gpg
    - apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/koide3_ppa.gpg] https://koide3.github.io/ppa/ubuntu2204 ./

  - name: Install libiridescence-dev
    apt:
      name: libiridescence-dev
    become: yes

  - name: Install libgtsam-points-dev
    apt:
      name: libgtsam-points-dev
    become: yes

  # - name: Install libgtsam-points-cuda12.2-dev
  #   apt:
  #     name: libgtsam-points-cuda12.2-dev
  #   become: yes

  # - name: Install libgtsam-points-cuda12.5-dev
  #   apt:
  #     name: libgtsam-points-cuda12.5-dev
  #   become: yes

